version: '1'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nome_do_banco_de_dados
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
    
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U seu_usuario -d nome_do_banco_de_dados"]
      interval: 5s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"

    depends_on:
      - db
